# 本地开发的项目配置文件

server:
  port: 6101
  servlet:
    context-path: /

# MySQL驱动以及连接参数
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_hackyle_com_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: hackyle
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 配置XML文件的位置
  configuration: # 相当于在MyBatis的主配置文件（MyBatis-config.xml）中配置
    # 一定要开启峰驼影射，否则就需要在Entity上手动设置属性名对应的字段名
    map-underscore-to-camel-case: true
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hackyle.blog.business.entity

# 文件存放路径
file-storage-path: D:\\A03-Program\\A-Programming\\GitHub\\Blog\\res.hackyle.com\\blog-dev\\
# 对外提供访问的路径，需要配置Nginx把请求解析到上个参数指定的目录下
file-domain: http://localhost/blog-dev/
# 图片水印的文本
water-mark-text: HACKYLE

